In [1]:
import numpy as np
import requests
from io import StringIO

1 Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [2]:
respone = requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
df = np.genfromtxt(StringIO(respone.text), delimiter=',', dtype=None, encoding=None)
# дивимось на сам dataframe
print(df)

[(5.1, 3.5, 1.4, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa') (4.6, 3.1, 1.5, 0.2, 'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, 'Iris-setosa') (5.4, 3.9, 1.7, 0.4, 'Iris-setosa')
 (4.6, 3.4, 1.4, 0.3, 'Iris-setosa') (5. , 3.4, 1.5, 0.2, 'Iris-setosa')
 (4.4, 2.9, 1.4, 0.2, 'Iris-setosa') (4.9, 3.1, 1.5, 0.1, 'Iris-setosa')
 (5.4, 3.7, 1.5, 0.2, 'Iris-setosa') (4.8, 3.4, 1.6, 0.2, 'Iris-setosa')
 (4.8, 3. , 1.4, 0.1, 'Iris-setosa') (4.3, 3. , 1.1, 0.1, 'Iris-setosa')
 (5.8, 4. , 1.2, 0.2, 'Iris-setosa') (5.7, 4.4, 1.5, 0.4, 'Iris-setosa')
 (5.4, 3.9, 1.3, 0.4, 'Iris-setosa') (5.1, 3.5, 1.4, 0.3, 'Iris-setosa')
 (5.7, 3.8, 1.7, 0.3, 'Iris-setosa') (5.1, 3.8, 1.5, 0.3, 'Iris-setosa')
 (5.4, 3.4, 1.7, 0.2, 'Iris-setosa') (5.1, 3.7, 1.5, 0.4, 'Iris-setosa')
 (4.6, 3.6, 1. , 0.2, 'Iris-setosa') (5.1, 3.3, 1.7, 0.5, 'Iris-setosa')
 (4.8, 3.4, 1.9, 0.2, 'Iris-setosa') (5. , 3. , 1.6, 0.2, 'Iris-setosa')
 (5. , 3.4, 1.6, 0.4, 'Iris-setosa') (5.2, 3.5, 1.5

In [3]:
#завантажуємо 4 стовпчика
df = np.loadtxt(StringIO(respone.text), delimiter=',', usecols=(0,1,2,3))
# якщо виводиться 2 числа (150, 4) це в нас є 2D масив, кількість цифр вказує на "масивність"
print('Розмір Data Frame: ', df.shape) 
# виводимо сам масив
print('Данні Data Frame: \n', df)

Розмір Data Frame:  (150, 4)
Данні Data Frame: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 

Порахувати mean, median, standard deviation для 1-ї колонки

In [4]:
print('Середнє значення : ', np.mean(df[:,0]))
print('Медіана : ', np.median(df[:,0]))
print('Середньоквадратичне відхилення : ', np.std(df[:,0]))

Середнє значення :  5.843333333333334
Медіана :  5.8
Середньоквадратичне відхилення :  0.8253012917851409


Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [5]:
#створимо Dataframe з позиціями для заміни елементів для вибора строк використовуєм choice з аргументом replace=False
row = np.random.choice(range(0,150), size=20, replace=False) 
column = np.random.randint(0,3,size=20)
repl_df = np.column_stack((row,column))
print(repl_df)

[[  6   0]
 [ 79   2]
 [ 48   1]
 [ 87   2]
 [136   0]
 [  8   0]
 [ 80   0]
 [ 58   1]
 [  5   2]
 [ 73   0]
 [ 95   1]
 [128   2]
 [140   1]
 [ 49   0]
 [ 24   0]
 [ 86   2]
 [ 94   2]
 [148   1]
 [ 70   2]
 [ 16   1]]


In [6]:
# змінюємо елементи по індексам на nan
df[repl_df[:,0],repl_df[:,1]] = np.nan
print(df)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 nan 0.4]
 [nan 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [nan 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 nan 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [nan 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 nan 1.5 0.2]
 [nan 3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Знайти позиції вставлених значень np.nan в 1-й колонці

In [7]:
if True in np.isnan(df[:,0]):
    index = np.where(np.isnan(df[:,0]))
    print('Індекса позицій nan :\n', index[0])
    position = index[0] + 1
    print('Позиція улемента nan :\n', position)

Індекса позицій nan :
 [  6   8  24  49  73  80 136]
Позиція улемента nan :
 [  7   9  25  50  74  81 137]


Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [8]:
filter_df = df[np.logical_and(df[:,2] > 1.5, df[:,0] < 5.0)]
print(filter_df)

[[4.8 3.4 1.6 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Замінити всі значення np.nan на 0

In [9]:
df[np.isnan(df)] = 0
print(df)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 0.  0.4]
 [0.  3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [0.  2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 0.  1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [0.  3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 0.  1.5 0.2]
 [0.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [10]:
uniq_value = np.unique(df, return_counts=True)
# Виводимо унікальні значення
print('Унікальні значення : ', uniq_value[0])
# Виводимо їх кількість
print('Кількість значень : ', uniq_value[1])

Унікальні значення :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
Кількість значень :  [20  6 28  7  7  1  1  8  4  7 20 20 26 11  5 12  7  7  6  6 12  6 11  5
  9 14  9 26 11 13  8 11  7  4  3  7  4  6  4  4  3  6  9  6  6  7 11 13
 17  6  3  8  9 11 11 10  5  8  8  4  9  8  5  3 10  3  5  1  1  3  1  1
  1  4  1]


Розбити масив по горизонталі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [11]:
two_df = np.vsplit(df,2)
first_df = two_df[0]
second_df = two_df[1]
#перевіряємо що дійсно 2 масива по 75 строк та 2 колонки
print('Розмір першого датафрейма : ', first_df.shape)
print('Розмір другого датафрейма : ', second_df.shape)

Розмір першого датафрейма :  (75, 4)
Розмір другого датафрейма :  (75, 4)


Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [12]:
# сортуємо перший массив за збільшенням
min_max = first_df[np.argsort(first_df[:,0])]
# сортуємо другий масив за зменшенням (сортуємо та здійснюємо реверс)
max_min = second_df[np.argsort(second_df[:,0])][::-1,]

print('Відфільтрований масив за зменшенням :\n', min_max, '\n')
print('Відфільтрований масив за збільшенням :\n', max_min)

Відфільтрований масив за зменшенням :
 [[0.  3.4 1.9 0.2]
 [0.  2.8 4.7 1.2]
 [0.  3.3 1.4 0.2]
 [0.  2.9 1.4 0.2]
 [0.  3.4 1.4 0.3]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.4 1.5 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 1.5 0.4]
 [5.1 3.8 1.5 0.3]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 2.7 3.9 1.4]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.3 0.  1.5 0.2]
 [5.4 3.9 0.  0.4]
 [5.4 0.  1.3 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.4 1.5 0.4]
 [5.4 3.7 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [5.5 2.3 4

Зібрати обидва массиви в одне ціле

In [13]:
aft_sort_df = np.concatenate([min_max, max_min], axis=0)
print("Масив після об'єднаяння : \n", aft_sort_df)

Масив після об'єднаяння : 
 [[0.  3.4 1.9 0.2]
 [0.  2.8 4.7 1.2]
 [0.  3.3 1.4 0.2]
 [0.  2.9 1.4 0.2]
 [0.  3.4 1.4 0.3]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.4 1.5 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 1.5 0.4]
 [5.1 3.8 1.5 0.3]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 2.7 3.9 1.4]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.3 0.  1.5 0.2]
 [5.4 3.9 0.  0.4]
 [5.4 0.  1.3 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.4 1.5 0.4]
 [5.4 3.7 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [5.5 2.3 4.  1.3]
 [5

Знайти найбільш часто повторюване значення в массиві

In [14]:
#знаходимо індекс більш повторювального числа із масива uniq_value
more_repeat_ind = np.where(uniq_value[1] == uniq_value[1].max())[0]
#знаходимо по індексу значення та виводимо його
more_repeat_val = uniq_value[0][more_repeat_ind]
print(more_repeat_val)

[0.2]


Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [15]:
# звичайна функциія для застосування vectorize
def do_matematic(mn, masiv):
    if masiv < mn:
        masiv = masiv * 2
    else:
        masiv = masiv / 4
    return masiv

Застосувати отриману функцію до 3-ї колонки

In [16]:
final_column = aft_sort_df[:,2]
mn_final_column = np.mean(final_column)
vect_do_matematic = np.vectorize(do_matematic, otypes=[float])
final_columns = vect_do_matematic(mn_final_column, final_column)
print('Приклад роботи функції з vectorize :\n',final_columns)

Приклад роботи функції з vectorize :
 [3.8   1.175 2.8   2.8   2.8   2.2   2.6   2.6   2.6   2.    3.    2.8
 2.6   3.2   3.2   2.8   3.2   2.8   3.    3.    6.6   3.    2.8   2.4
 2.6   3.2   3.2   3.    7.    2.8   3.2   3.8   3.    3.2   2.8   3.4
 3.    3.    2.8   3.    0.975 2.8   3.    3.    0.    2.6   3.4   3.
 3.    2.6   1.    2.8   0.975 0.9   1.125 3.    1.125 3.4   1.025 2.4
 0.    1.05  1.    1.175 1.    1.125 1.225 1.175 1.075 1.125 1.15  1.15
 1.1   1.225 1.175 1.6   1.675 1.725 1.675 1.525 1.65  1.525 1.575 1.45
 1.525 1.5   1.475 1.35  1.275 1.425 1.475 1.2   1.375 1.425 1.4   1.45
 0.    1.425 1.3   1.25  1.1   1.275 1.3   1.375 1.45  0.    1.4   1.325
 1.375 1.325 1.275 1.5   0.    1.4   1.225 1.25  1.075 1.35  1.2   1.4
 1.225 1.15  1.275 1.125 1.125 1.2   1.25  1.275 1.275 1.275 1.    0.975
 1.275 1.05  1.25  0.    1.05  1.025 1.025 0.    1.225 1.    1.1   0.925
 1.125 6.    6.6   1.125 1.4   0.95 ]


Аналогічна функція без vectorize

In [17]:
def mathematic(col):
    mn = np.mean(col)
    new_col = np.where(col < mn, col*2, col/4)
    return new_col

In [18]:
non_vectorize = mathematic(aft_sort_df[:,2])
print(non_vectorize)

[3.8   1.175 2.8   2.8   2.8   2.2   2.6   2.6   2.6   2.    3.    2.8
 2.6   3.2   3.2   2.8   3.2   2.8   3.    3.    6.6   3.    2.8   2.4
 2.6   3.2   3.2   3.    7.    2.8   3.2   3.8   3.    3.2   2.8   3.4
 3.    3.    2.8   3.    0.975 2.8   3.    3.    0.    2.6   3.4   3.
 3.    2.6   1.    2.8   0.975 0.9   1.125 3.    1.125 3.4   1.025 2.4
 0.    1.05  1.    1.175 1.    1.125 1.225 1.175 1.075 1.125 1.15  1.15
 1.1   1.225 1.175 1.6   1.675 1.725 1.675 1.525 1.65  1.525 1.575 1.45
 1.525 1.5   1.475 1.35  1.275 1.425 1.475 1.2   1.375 1.425 1.4   1.45
 0.    1.425 1.3   1.25  1.1   1.275 1.3   1.375 1.45  0.    1.4   1.325
 1.375 1.325 1.275 1.5   0.    1.4   1.225 1.25  1.075 1.35  1.2   1.4
 1.225 1.15  1.275 1.125 1.125 1.2   1.25  1.275 1.275 1.275 1.    0.975
 1.275 1.05  1.25  0.    1.05  1.025 1.025 0.    1.225 1.    1.1   0.925
 1.125 6.    6.6   1.125 1.4   0.95 ]


In [19]:
#перевіряємо чи дорівнюють одна одній:
if final_columns.all() == non_vectorize.all():
    print('Congratulation 🥳')

Congratulation 🥳
